AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demo Organization Api Environment Assets

Parameters:
  ApiGateway:
    Description: Ref of API Gateway
    Type: String
  StageName:
    Description: Deployment stage for API Gateway
    Type: String
  DeploymentId:
    Description: Current Deployment Id
    Type: String
  Version:
    Description: Deployment version number
    Type: String

Resources:

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref StageName
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref DeploymentId
      Variables:
        env: !Ref StageName
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
          MetricsEnabled: true

  # Moodle Tenant alian
  PostMoodleTenantLambdaFunctionAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !ImportValue OrganizationGetHandlerArn
      FunctionVersion: !ImportValue MoodleTenantDetailVersion
      Name: !Ref StageName

  ## Invoke Permissions
  PostMoodleTenantLambdaFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - GetAllOrganizationsLambdaFunctionAlias
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName: !Join [":", [ !ImportValue OrganizationGetHandlerArn, !Ref StageName]]
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/${StageName}/*
